chore: Update zookeeper to 3.8.4
kserve/modelmesh pull request #136
Opened 2024-03-20 19:47 UTC by israel-hdez

This is to move away from CVE-2024-23944: information disclosure.

2024-03-21 22:03 UTC, rafvasq commented
Seems like the tests never finish/fail. At first glance there's a message `SLF4J: Class path contains multiple SLF4J bindings.` and I haven't been able to connect that to the Zookeeper update yet, but it seems like upgrading `<slf4j-version>1.7.36</slf4j-version>` to latest (v2.0.12) works. I can continue to look into it, not familiar with these frameworks.

2024-03-22 17:32 UTC, israel-hdez commented
> seems like upgrading `<slf4j-version>1.7.36</slf4j-version>` to latest (v2.0.12) works

I did this and now the tests are finishing, but an error is issued.
I'll also try to look at it closer, but I can't promise progress, given I'm not familiar with the codebase.

2024-03-22 19:58 UTC, rafvasq commented
> > seems like upgrading `<slf4j-version>1.7.36</slf4j-version>` to latest (v2.0.12) works
> 
> I did this and now the tests are finishing, but an error is issued. I'll also try to look at it closer, but I can't promise progress, given I'm not familiar with the codebase.

Thanks for trying that. I looked into it more and noticed that [they migrated to `logback` in 3.8](https://issues.apache.org/jira/browse/ZOOKEEPER-4427). For now at least, we can exclude it [here](https://github.com/kserve/modelmesh/blob/8c020c2097fc9313563c77d9ff78e498e784fd92/pom.xml#L530-L535): 

```xml
<dependency>
  <!-- override litelinks' versions with newer to avoid CVE -->
  <groupId>org.apache.zookeeper</groupId>
  <artifactId>zookeeper</artifactId>
  <version>${zookeeper-version}</version>
  <exclusions>
    <exclusion>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

2024-03-25 12:54 UTC, rafvasq requested changes
In case you missed it, please revert `slf4j-version` too and hopefully the tests pass.

2024-03-26 00:42 UTC, israel-hdez commented
> In case you missed it, please revert `slf4j-version` too and hopefully the tests pass.

@rafvasq I just updated the PR. Looks like it is working :-)

2024-03-26 13:41 UTC, rafvasq approved these changes
/lgtm

2024-03-26 13:43 UTC, merged